# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/kinetics/val_data_bone.npy
  label_path: ./data/kinetics/val_label.pkl
  debug: False

# model
model: model.agcn.Model
model_args:
  num_class: 400
  num_person: 2
  num_point: 18
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: 0
test_batch_size: 64
weights: ./pre_train/ki_agcn_bone.pt


work_dir: ./work_dir/kinetics/agcn_test_bone
model_saved_name: ./runs/ki_agcn_test_bone
save_score: True